name: CI (non-release)
on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      release: false
      version-operation: set-prerelease
      version-prerelease: '${commit_digest}'
      version-commit-message: "build ${version}"
