name: Release
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: release

  release:
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build

    secrets:
      github-app-secret-key: ${{ secrets.secrets.GARDENER_GITHUB_ACTIONS_PRIVATE_KEY }}

    with:
      component-descriptor: ${{ needs.build.outputs.base-component-descriptor }}
      release-commit-objects: ${{ needs.build.outputs.version-commit-objects }}
      release-commit-digest: ${{ needs.build.outputs.version-commit-digest }}
      next-version: bump-minor
