name: Release
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot

  release:
    uses: ccwienk-org/cc-utils/.github/workflows/release.yaml@master

    secrets: inherit

    with:
      next-version: bump-minor
